server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/ehealthbook/api/auth/**
          filters:
            - StripPrefix=1
        - id: user-management-service
          uri: http://localhost:8082
          predicates:
            - Path=/ehealthbook/api/user/**
          filters:
            - StripPrefix=1
jwt:
  secret: "yD$5Jc@9Lh%K1vX7tZpQ!rN&Wx*GfC3B"